workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: release
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Set up key.properties file for code signing
        script: |
          flutter drive --driver=integration_test/driver.dart --target=integration_test/formWidgets_test.dart    
      - name: Build Android app
        script: flutter build apk --release
    artifacts:
      - android-app-bundle build-universal-apk \
        --bundle 'project_directory/build/**/outputs/**/*.aab' \
        --ks /tmp/keystore.keystore \
        --ks-pass $FCI_KEYSTORE_PASSWORD \
        --ks-key-alias $FCI_KEY_ALIAS \
        --key-pass $FCI_KEY_PASSWORD