name: CI/CD
on:
  push:
    branches:
      - master

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        env:
          GITHUB_TOKEN: $({ secrets.TOKEN })
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          api-level: 29
          profile: ${{ matrix.device }}
          script: |
            flutter drive --driver=integration_test/driver.dart --target=integration_test/formWidgets_test.dart
