name: CI/CD
on:
  push:
    branches:
      - master

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: flutter drive --driver=integration_test/driver.dart --target=integration_test/formWidgets_test.dart
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck
