name: CI/CD
on:
  push:
    branches:
      - master

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: $({ secrets.TOKEN })
          script: |
            flutter drive --driver=integration_test/driver.dart --target=integration_test/formWidgets_test.dart
