name: Flutter CI

on:
  push:
    branches:
    - master
  commit_comment:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
    - run: flutter drive --driver=integration_test/driver.dart --target=integration_test/formWidgets_test.dart
