name: Flutter CI

on:
  push:
    branches:
    - master
  commit_comment:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Run a one-line script
       run: echo "Everything is okay"
